name: Swagger UI Field Formatter
description: Provides a Swagger UI field formatter for File and Link fields.

dependencies:
  - drupal:file

type: module
core_version_requirement: ^9.4 || ^10.0

# Information added by Drupal.org packaging script on 2023-03-27
version: '4.0.0'
project: 'swagger_ui_formatter'
datestamp: 1679924424
